### ISSUE TITLE
[META] New Stage Screen Improvements

### ISSUE THREAD

**Issue by jthrilly** [complexdatacollective/Architect#677]
The new stage screen would benefit from a revision.

- [x] Interfaces should be displayed in a filterable list
- [x] Each interface section should show the interface name, a its preview image, and perhaps also text about it.
- [x] In additional to the list being filterable by name, it should also be filterable by "tags"
- [x] Tags should be interface affordances/functionality: "Create nodes", "Create edges", "Ego data", "Add Node Attribtues", "Add Edge Attribtues", "Use Roster Data"
- [ ] Revisit the idea of a "wizard" that can reccomend an interface. Could be a simple branching tree. Ask the user: "Do you want to create an entity, add attributes to entities, or both?" and so on.
